### ISSUE TITLE
Kindly give commands or specific links to download the pre-req

### ISSUE THREAD

**Issue by satyamsah** [airavata-courses/jerrin92#1]
Hi , Could you please specify link or specific command to run the pre-req(System Requirements) . Or else specific link to run a those commands via links. So that it would be easier for me to install all the pre-req and test the application

**Comment by jerrin92** [comment]
Yup, sure! What is the environment that you are trying to run this on?

**Comment by satyamsah** [comment]
ubuntu

**Comment by jerrin92** [comment]
I have added the comments, please go through the same. If you are still facing issues, do let me know the installation, that you are having trouble with.

**Comment by satyamsah** [comment]
error while executing : node app.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'mysql'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntuaws/jerrin92/nodemon/app.js:2:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by jerrin92** [comment]
Try `npm install mysql` in the directory

**Comment by satyamsah** [comment]
Hi Jerry,
Is your  db port "3016" under getLoad.py . Normally it is 3306

**Comment by jerrin92** [comment]
I have made some changes to the code, please pull once again. And I have added a wiki page regarding the configuration for the same. Please go through the same and let me know if you are facing any issues.

Please also ensure that the MySQL credentials and port are configured as per your local MySQL installation. Update the MySQL details in nodemon/app.js, nodemon2/app.js, getLoad.py and getInterrupts.py

**Comment by satyamsah** [comment]
I have made everything up and running but no response of http://localhost:4200. Kindly let me know when can you be available for screen share online. Kindly could you update the readme / wiki . I think your port entry for mysql  are missing some files.

**Comment by jerrin92** [comment]
Okay, for quick trouble shooting, could you check if you can view any results on localhost:3000 and localhost:3001

**Comment by satyamsah** [comment]
Yes , both localhost:3000 and localhost:3001 are up

**Comment by jerrin92** [comment]
- Change directory to userInterface
- `npm install`
-  `ng serve`
-  Visit http://localhost:4200

However, if you are not seeing any output in either of those pages i.e localhost:3000 and localhost:3001. Please paste, the output that you get while visiting those pages.

**Comment by satyamsah** [comment]
![screenshot from 2017-09-02 12-11-51](https://user-images.githubusercontent.com/9192353/29997067-5d4368d2-8fd8-11e7-9931-d70fd2848a6f.png)


no response even after ng serve

**Comment by jerrin92** [comment]
Could you check the angular-cli version of your system and the cli version in the userInterface directory.

Run `ng -v` in userInterface directory and anywhere else in the system

and paste the output of the same

**Comment by satyamsah** [comment]
Outside :
Mg++ version:
	Mg++ 1.5beta1 (formerly MicroGnuEmacs Adv.)
(myenv) ubuntuaws@ubuntuaws-VirtualBox:~$ 

Under userInterface;
tmp/myenv/jerrin92/Assignment1/userInterface$ ng -v
Mg++ version:
	Mg++ 1.5beta1 (formerly MicroGnuEmacs Adv.)

**Comment by satyamsah** [comment]
![screenshot from 2017-09-02 18-50-37](https://user-images.githubusercontent.com/9192353/29999266-e6ff52f2-900f-11e7-86c1-5e521fb80519.png)


As you wrote in readme I have run of the five services, but then also http://localhost:4200  is not responding

**Comment by jerrin92** [comment]
Please check the comment by @sidjoshi001

> https://github.com/angular/angular-cli/issues/3759

I am not pretty sure if you need to add the alias in .bashrc though

**Comment by satyamsah** [comment]
sorry , I am not sure what are you referring to ?

**Comment by jerrin92** [comment]
Try the following commands,

`sudo apt remove ng-common`
`npm cache clean`

and then `cd userInterface` and `ng serve`

**Comment by satyamsah** [comment]
I thinkthe situation got more complex now: 
ng serve
bash: /usr/bin/ng: No such file or directory

**Comment by jerrin92** [comment]
Try `npm install angular` followed by `npm start` instead of `ng serve`

**Comment by satyamsah** [comment]
after a lot of effort , it successfully got deployed.As a feedback please update the readme correctly , so that next time it wont be that much time consuming. Please give use case what does your project do in a paragraph.

**Comment by jerrin92** [comment]
Thanks Satyam, for the comments and effort. I shall update the readme
