### ISSUE TITLE
Communication between the microservices

### ISSUE THREAD

**Issue by sachinkariyattin** [airavata-courses/jerrin92#3]
@jerrin92 
I was able to follow all the steps and see the output through http://localhost:4200. But, I am not clear about the overall flow of execution.
Could you please explain the architecture of the system?. I just wanted to know how the services are communicating between each other

**Comment by jerrin92** [comment]
As you might have seen the project involves getting the system stats. So, there are 2 graphs of which one of them is Load and the other is Interrupt count. The data collection begins at the Python scripts getInterrupts.py and getLoad.py. The scripts get the data and insert it into the mysql. There are 2 node services that read from the db and converts it into json object and serves through http. The userInterface which is in angular would get/request the data for the 2 graphs from these services.

**Comment by jerrin92** [comment]
I have added a new architecture diagram in the main repo as well
