### ISSUE TITLE
Assignment 1: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/jerrin92#4]
Hi Jerrin,

Could you please provide a system architecture diagram so that it would be easier to identify each component of the system and how they interact.

Also the npm install step in nodemon and nodemon2 threw an error for mysql module missing.
I think it is a missing mysql dependency which I encountered while installing them using the steps provided. Please incorporate it in the dependencies.

Also, Please host your python files on a web server e.g. Flask if possible.

I was able to run your application after additionally installing mysql modules in the nodemon and nodemon2 apps.

**Comment by jerrin92** [comment]
Yup, i have made the changes in Assignment so as its dockerized you don't have to perform npm install mysql. I have added the architecture diagram in the assignment2 directory as well
