### ISSUE TITLE
Not able to run docker command

### ISSUE THREAD

**Issue by harsha161992** [airavata-courses/jerrin92#5]
Hi,

I followed the wiki page of Assignment 2 and I am not able to run docker for your services.
When I try to run ms1:
![2017-09-13 1](https://user-images.githubusercontent.com/17470082/30393623-c4ccd5c4-988e-11e7-98a7-b22945e5901b.png)

I am getting the same error with ms2.

Please check the issue.

**Comment by jerrin92** [comment]
From the error message above it seems that its probably an issue related to run.sh rather the container. So, once you pull the github repo to your local repo the .sh files might be inserted with WINDOWS/DOS style line endings. 

But that being said I shall look into it further.
